######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 24 11:38:33 2019
######################################################################

TEMPLATE = app
TARGET = com_tester
DEFINES += QT_DEPRECATED_WARNINGS
#CONFIG += c++11
MOC_DIR=moc
OBJECTS_DIR=obj


QT -= gui
QT *= network widgets xml serialport

INCLUDEPATH += . \
            $$PWD \
            $$PWD/../../lib \
            $$PWD/../../lib/ui_h
            
            
                                    
DEPENDPATH += $$PWD/../../lib/build
unix:!macx: LIBS += -L$$PWD/../../lib/build -llib

# Input
HEADERS += mainform.h \
        comobj.h \
    fileworker.h \
    comparams_struct.h

SOURCES += main.cpp \
	mainform.cpp \
        comobj.cpp \
    fileworker.cpp

