#!/bin/bash

# user vars
PWD_DIR=$(pwd)
REPO_DIR=$PWD_DIR/../../..
PROG_NAME=isoworker
PROG_DIR=$REPO_DIR/$PROG_NAME
BUILD_DATA_FOLDER=build_data
SRC_DIR=$BUILD_DATA_FOLDER/src/$PROG_NAME
DEBDIR=isoworker-qt5

#выхлоп значений переменных (для информации)
echo "Starting RPM build package!!"
echo "--------------------------------"
echo "DEBDIR: $DEBDIR"
echo "REPO_DIR: $REPO_DIR"
echo "SRC_DIR: $SRC_DIR"
echo "PROG_NAME: $PROG_NAME"
echo "--------------------------------"
echo ""
sleep 2

#подготовка отдельной папки со всеми необходимыми данными для создания rpm пакета (рядом с makedistr)
cd $PWD_DIR
echo "PREPARE DATA FOR PACKAGING ............"
if [ -d $SRC_DIR ]; then
    echo "removing old dir ($SRC_DIR)...."
    rm -rf $SRC_DIR
    sleep 0.5
fi

echo "create building dir: $BUILD_DATA_FOLDER"
mkdir -p $SRC_DIR
cd $SRC_DIR
sleep 1

echo "copy project dir: $PROG_NAME"
cp $PROG_DIR/*.cpp .
cp $PROG_DIR/*.h .
cp $PROG_DIR/*pro .
cp -r $PROG_DIR/ui .
cd ..

echo -e "copy my libs dir \n\n"
cp -r $REPO_DIR/libs .
sleep 1


#запуск  сборки deb-пакета
echo "Starting build DEB-package, cmd=[debuild -us -uc -b] .........."
sleep 2
cd $PWD_DIR
cd $BUILD_DATA_FOLDER
debuild -us -uc -b
echo -e "Building ended! \n"
sleep 1


#проверка результата выполнения сценария создания rpm пакета (rpmbuild)
RR_CODE=$?
if [ $RR_CODE -ne 0 ]; then 
    echo ""
    echo "WARNING: RPM building breaked, result code: $RR_CODE"
    exit -1;
fi
echo "RPM building done!"
echo ""
sleep 1

#удаление старых данных
echo "removind old data ......."
cd $PWD_DIR
if [ -d $SRC_DIR ]; then
    echo "  removing ($SRC_DIR)"
    rm -rf $SRC_DIR
    sleep 0.5
fi
if [ -d $BUILD_DATA_FOLDER/src/libs ]; then
    echo "  removing ($BUILD_DATA_FOLDER/src/libs)"
    rm -rf $BUILD_DATA_FOLDER/src/libs
    sleep 0.5
fi
echo 'clean PWD section .... '
if [ -f *.ddeb ]; then rm *.ddeb; fi
if [ -f *.changes ]; then rm *.changes; fi
if [ -f *.buildinfo ]; then rm *.buildinfo; fi
if [ -f *.build ]; then rm *.build; fi
sleep 1

cd $PWD_DIR
cd $BUILD_DATA_FOLDER/debian
echo 'clean debian section .....'
if [ -d .debhelper ]; then rm -rf .debhelper; fi
if [ -d $DEBDIR ]; then rm -rf $DEBDIR; fi
if [ -f $DEBDIR.debhelper.log ]; then rm $DEBDIR.debhelper.log; fi
if [ -f $DEBDIR.substvars ]; then rm $DEBDIR.substvars; fi
if [ -f files ]; then rm files; fi
sleep 1

echo "done"
sleep 1

echo "FINISHED ALL!!!"
sleep 1
exit $?

