######################################################################
# Automatically generated by qmake (3.1) Mon Apr 18 14:33:36 2022
######################################################################

TEMPLATE = app
TARGET = smb_test
DEFINES += QT_DEPRECATED_WARNINGS
MOC_DIR=moc
OBJECTS_DIR=obj
UI_DIR=uic

QT -= gui
QT *= network widgets


INCLUDEPATH += . \
            $$PWD \
            $$PWD/../libs/base \
            $$PWD/../libs/base/ui_h


////////////////////////////////////////
#path for libs files
DEPENDPATH += $$PWD/../libs/base/build
#include libs
unix:!macx: LIBS += -L$$PWD/../libs/base/build/ -llbase


# Input
HEADERS += $$PWD/dsnsfilestruct.h \
    $$PWD/mainwidget.h


SOURCES += $$PWD/main.cpp \
    $$PWD/dsnsfilestruct.cpp \
    $$PWD/mainwidget.cpp


FORMS += $$PWD/mainwidget.ui

